# Generated by Django 4.2.3 on 2023-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_monitor_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
