# Generated by Django 4.2.3 on 2023-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_monitor_backend', '0002_accesslog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
