# Generated by Django 4.2.3 on 2023-07-14 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_monitor_backend', '0003_alter_accesslog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
