# Generated by Django 4.2.3 on 2023-07-17 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_monitor_backend', '0004_alter_accesslog_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcurrencypair',
            old_name='currency_pair',
            new_name='pair',
        ),
        migrations.RemoveField(
            model_name='savedcurrencypair',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='savedcurrencypair',
            name='notification_threshold',
        ),
        migrations.RemoveField(
            model_name='savedcurrencypair',
            name='user',
        ),
        migrations.AddField(
            model_name='savedcurrencypair',
            name='users',
            field=models.ManyToManyField(related_name='saved_currency_pairs', to=settings.AUTH_USER_MODEL),
        ),
    ]
